version: "3.9"

services:
  app:
    image: smopuim85/coursework_5:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "80:80"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
